version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pantry
      POSTGRES_USER: pantry
      POSTGRES_PASSWORD: pantry
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://pantry:pantry@db:5432/pantry
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-devkey}
      - SPOONACULAR_KEY=${SPOONACULAR_KEY:-}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
